version: 2.1

jobs:
  build-and-test:
    docker:
      - image: cimg/node:20.1  # Node.js 20 + npm already installed

    steps:
      - checkout

      - run:
          name: Install dependencies
          command: npm install

      - run:
          name: Build project
          command: npm run build

workflows:
  react-build:
    jobs:
      - build-and-test
